apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: inventory
  annotations:
    cnrm.cloud.google.com/deletion-policy: abondon
    iam.gke.io/gcp-service-account: argocd-fleet-admin@learnwebcoding-372523.iam.gserviceaccount.com
spec:
  charset: UTF8
  collation: en_US.UTF8
  instanceRef:
    name: {{ .Values.deployment.metadata.name }}