apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: dbmonitor
  annotations:
    cnrm.cloud.google.com/deletion-policy: abondon
    iam.gke.io/gcp-service-account: argocd-fleet-admin@learnwebcoding-372523.iam.gserviceaccount.com
spec:
  instanceRef:
    name: {{ .Values.deployment.metadata.name }}
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        name: sqluser-dbmonitor
        key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: sqluser-dbmonitor
  annotations:
    cnrm.cloud.google.com/deletion-policy: abondon
    iam.gke.io/gcp-service-account: argocd-fleet-admin@learnwebcoding-372523.iam.gserviceaccount.com
data:
  password: cGFzc3dvcmQ=
